### PR TITLE
PUT /events/{id}, GET /events/friendTag{id}

### PR DESCRIPTION
**Pull request by Shane-M-1**
endpoints for PUT event by id and GET events by friendTag

### CODE REVIEW

**Review by SeabertYuan — CHANGES_REQUESTED** [review]
GET endpoints look good but I think I've done a more thorough PUT endpoints in PR #32

**Comment by Shane-M-1** [comment]
> more thorough PUT endpoints in PR #32

Agreed. I removed my PUT endpoint

**Review by SeabertYuan — CHANGES_REQUESTED** [review]
Make sure that the updateEventById method is also removed from IEventService

**Review by SeabertYuan — APPROVED** [review]
Looks good to me!

**Pull request merged**
